## Step 1:
Imported Numply library and created an alias for it.
A 2D 4x4 Numpy array of data type integer.

In [12]:
#step1
import numpy as np

In [13]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]])

In [14]:
print(a.shape)

(4, 4)


In [15]:
print(a.dtype)

int64


## Step 2:
The code prints the second column and the list row of the array above.

In [16]:
#step2
print("Second column:", a[:,1])
print("Last row:", a[-1, :])

Second column: [ 2  6 10 14]
Last row: [13 14 15 16]


## Step 3:
A 2D 3x3 Numpy array.
mean() function used for calculating the mean of the "arr" array and printing values greater than it.

In [17]:
#step3
arr = np.array([
    [1,16,30],
    [25,80,42],
    [7,22,50]
])


In [18]:
print("Array mean:",arr.mean())
print("Values greater than array mean:", arr[arr > arr.mean()])

Array mean: 30.333333333333332
Values greater than array mean: [80 42 50]


# Step 4:
A 2D 3x5 Numpy array and a 1D 1x5 array.
since both arrays have 5 columns, it allows broadcasting.
A manual and a broadcasted result show consistency when compaired using the == operator.

In [19]:
#step4

twoD = np.array([
    [1,0,5,7,2],
    [8,4,6,2,9],
    [7,3,10,8,1],
])

oneD = np.array([1,6,3,5,2])



In [20]:
print(twoD.shape)
print(oneD.shape)

(3, 5)
(5,)


In [21]:
oneD_replicated = np.array(
                [[1,6,3,5,2],
                 [1,6,3,5,2],
                 [1,6,3,5,2]])

In [22]:
manual_result = twoD + oneD_replicated
print(manual_result)

[[ 2  6  8 12  4]
 [ 9 10  9  7 11]
 [ 8  9 13 13  3]]


In [23]:
broadcast_result= twoD + oneD
print(broadcast_result)

[[ 2  6  8 12  4]
 [ 9 10  9  7 11]
 [ 8  9 13 13  3]]


In [57]:
manual_result == broadcast_result

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])